In [1]:
import pandas as pd
from pathlib import Path

In [3]:
csv_path = Path('../Sources/train.csv')
df = pd.read_csv(csv_path)
df.head()

,AccountAge,MonthlyCharges,TotalCharges,SubscriptionType,PaymentMethod,PaperlessBilling,ContentType,MultiDeviceAccess,DeviceRegistered,ViewingHoursPerWeek,...,ContentDownloadsPerMonth,GenrePreference,UserRating,SupportTicketsPerMonth,Gender,WatchlistSize,ParentalControl,SubtitlesEnabled,CustomerID,Churn
0,20,11.055215,221.104302,Premium,Mailed check,No,Both,No,Mobile,36.758104,...,10,Sci-Fi,2.176498,4,Male,3,No,No,CB6SXPNVZA,0
1,57,5.175208,294.986882,Basic,Credit card,Yes,Movies,No,Tablet,32.450568,...,18,Action,3.478632,8,Male,23,No,Yes,S7R2G87O09,0
2,73,12.106657,883.785952,Basic,Mailed check,Yes,Movies,No,Computer,7.395160,...,23,Fantasy,4.238824,6,Male,1,Yes,Yes,EASDC20BDT,0
3,32,7.263743,232.439774,Basic,Electronic check,No,TV Shows,No,Tablet,27.960389,...,30,Drama,4.276013,2,Male,24,Yes,Yes,NPF69NT69N,0
4,57,16.953078,966.325422,Premium,Electronic check,Yes,TV Shows,No,TV,20.083397,...,20,Comedy,3.616170,4,Female,0,No,No,4LGYPK7VOL,0

In [4]:
df.columns

Index(['AccountAge', 'MonthlyCharges', 'TotalCharges', 'SubscriptionType',
       'PaymentMethod', 'PaperlessBilling', 'ContentType', 'MultiDeviceAccess',
       'DeviceRegistered', 'ViewingHoursPerWeek', 'AverageViewingDuration',
       'ContentDownloadsPerMonth', 'GenrePreference', 'UserRating',
       'SupportTicketsPerMonth', 'Gender', 'WatchlistSize', 'ParentalControl',
       'SubtitlesEnabled', 'CustomerID', 'Churn'],
      dtype='object')

In [6]:
charges_type_group = ['MonthlyCharges', 'SubscriptionType']
payment_billing_group = ['PaymentMethod', 'PaperlessBilling']
content_group = ['ContentType', 'GenrePreference']
viewing_group = ['ViewingHoursPerWeek', 'AverageViewingDuration', 'WatchlistSize']
rating_n_age_group = ['AccountAge', 'UserRating']
device_group = ['DeviceRegistered', 'MultiDeviceAccess']
other_group = ['ParentalControl', 'SubtitlesEnabled', 'Gender']

In [7]:
df[viewing_group].head()

   ViewingHoursPerWeek  AverageViewingDuration
0            36.758104               63.531377
1            32.450568               25.725595
2             7.395160               57.364061
3            27.960389              131.537507
4            20.083397               45.356653